name: Java install openjdk-8-jdk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven

      - name: sudo apt-get update
        run: sudo apt-get update

      - name: sudo apt-get install openjdk-8-jdk
        run: sudo apt-get install openjdk-8-jdk -y

      - name: openjdk-8-jre
        run: sudo apt-get install openjdk-8-jre -y

      - name: java -version
        run: mvn -B package --file pom.xml

      - name: gift.war
        run: ls -la && ip address

#      - name: gift.war
#        run: java -jar target/solution-0.0.1-SNAPSHOT.jar

#      - name: exec:java
#        run: cd WEB-INF
